config/routes.rb
Rails.application.routes.draw do
  root 'prefectures#index'
  resources :prefectures, only: [:index], shallow: true do
    resources :cities, only: [:index] do
      resources :weather_forecasts, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :prefecture
  has_many :weather_forecasts, dependent: :destroy
  has_many :statistics, dependent: :destroy
  validates_presence_of :name, :romaji, :location_id
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :cities, dependent: :destroy
  validates :name, presence: true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :city
  validates :date, presence: true

  scope :recent, -> { order(date: :desc) }

  def weather_condition_d
    case weather_d
    when '快晴'
      '快晴d'
    when /晴/
      '晴れd'
    when /雪/
      '雪d'
    when '大雨'
      '雨d'
    when /雨/
      '小雨d'
    when /曇/
      '曇りd'
    else
      '霧d'
    end
  end

  def weather_condition_n
    case weather_n
    when '快晴'
      '快晴n'
    when /晴/
      '晴れn'
    when /雪/
      '雪n'
    when '大雨'
      '雨n'
    when /雨/
      '小雨n'
    when /曇/
      '曇りn'
    else
      '霧n'
    end
  end

  def self.today
    select do |s|
      s.date.strftime('%m%d') == Time.current.strftime('%m%d')
    end
  end

  def self.tomorrow
    select do |s|
      s.date.strftime('%m%d') == Time.current.tomorrow.strftime('%m%d')
    end
  end
end

app/models/weather_forecast.rb
class WeatherForecast < ApplicationRecord
  belongs_to :city
  validates_presence_of :temp_max, :temp_min, :weather_id, :date, :aquired_at

  scope :today, -> { where(date: Date.current.all_day).order(date: :desc) }
  scope :tomorrow, -> { where(date: Date.current.tomorrow.all_day).order(date: :desc) }
  scope :today_at_noon, -> { where(date: Date.today.since(12.hours)) }

  def weather_condition
    case weather_id
    when 200..232 then '雷雨'
    when 300..321 then '霧'
    when 500..501 then '小雨'
    when 502..531 then '雨'
    when 600..622 then '雪'
    when 800..801 then '快晴'
    when 802      then '晴れ'
    when 803..804 then '曇り'
    end
  end

  def daytime?
    date.hour >= 6 && date.hour < 18
  end

  def temp_avg
    (temp_max + temp_min) / 2
  end

  def rainfall_avg
    rainfall / 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @prefecture = Prefecture.find(params[:prefecture_id])
    @cities = @prefecture.cities
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def index
    @prefectures = Prefecture.all
    @weather_forecasts = WeatherForecast.all
    city_list = ['札幌', '仙台', '東京', '新潟', '金沢', '大阪', '高知', '広島', '福岡', '那覇']
    @weather_forecasts = WeatherForecast.joins(:city).where(cities: { name: city_list }).today_at_noon
  end
end

app/controllers/weather_forecasts_controller.rb
class WeatherForecastsController < ApplicationController
  def index
    @city = City.find(params[:city_id])
    @weather_forecasts = WeatherForecast.where(city: @city)
    @statistics = Statistic.where(city: @city).recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/weather_forecasts_helper.rb
module WeatherForecastsHelper
end

app/views/cities/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <h1><%= @prefecture.name %></h1>
  <% @cities.each do |city| %>
    <h3><%= link_to city.name, city_weather_forecasts_path(city) %></h3>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'WeatherNews', root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '都道府県で調べる', root_path %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newshy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/prefectures/index.html.erb
<div class="map-area">
  <%= image_tag 'japan.png' %>
  <% @weather_forecasts.each do |forecast| %>
    <div class="<%= forecast.city.romaji %> spot">
      <%= link_to prefecture_cities_path(forecast.city.prefecture) do %>
        <li><%= forecast.city.name %></li>
        <li><%= image_tag "#{forecast.weather_condition}d.png" %></li>
        <li><%= "#{forecast.temp_max} / #{forecast.temp_min}" %></li>
      <% end %>
    </div>
  <% end %>
</div>
<div class="pref-area">
  <ul>
    <li>
      <span id="hokkaido">北海道地方</span>
      <%= link_to @prefectures[0].name, prefecture_cities_path(@prefectures[0]) %>
    </li>
    <li>
      <span id="tohoku">東北地方</span>
      <% @prefectures[1..6].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="kanto">関東地方</span>
      <% @prefectures[7..13].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="chubu">中部地方</span>
      <% @prefectures[14..22].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="kansai">関西地方</span>
      <% @prefectures[23..29].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="chugoku">中国地方</span>
      <% @prefectures[30..34].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="shikoku">四国地方</span>
      <% @prefectures[35..38].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="kyushu">九州地方</span>
      <% @prefectures[39..45].each do |pref| %>
        <%= link_to pref.name, prefecture_cities_path(pref) %>
      <% end %>
    </li>
    <li>
      <span id="okinawa">沖縄地方</span>
      <%= link_to @prefectures[46].name, prefecture_cities_path(@prefectures[46]) %>
    </li>
  </ul>
</div>

app/views/weather_forecasts/_forecast_area.html.erb
<div class="row forecast">
  <div class="forecast-head">
    <strong class="date"><%= weather_forecasts.first.date.strftime('%m月%d日') %>の天気</strong>
    <strong class="max"><%= weather_forecasts.maximum(:temp_max).round %>℃</strong> / 
    <strong class="min"><%= weather_forecasts.minimum(:temp_min).round %>℃</strong>
    <span class="feels">体感温度：<%= weather_forecasts.average(:temp_feel).round %>℃</span>
  </div>
  <table>
    <thead>
      <th>時間</th>
      <th>0-3</th>
      <th>3-6</th>
      <th>6-9</th>
      <th>9-12</th>
      <th>12-15</th>
      <th>15-18</th>
      <th>18-21</th>
      <th>21-24</th>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <% weather_forecasts.each do |forecast| %>
          <% if forecast.daytime? %>
            <td><%= image_tag "#{forecast.weather_condition}d.png" %></td>
          <% else %>
            <td><%= image_tag "#{forecast.weather_condition}n.png" %></td>
          <% end %>
        <% end %>
      </tr>
      <tr>
        <td>気温</td>
        <% weather_forecasts.each do |forecast| %>
          <td><%= forecast.temp_avg.round(1) %></td>
        <% end %>
      </tr>
      <tr>
        <td>降水/h</td>
        <% weather_forecasts.each do |forecast| %>
          <td><%= forecast.rainfall ? forecast.rainfall_avg.round(1) : '-' %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<div class="row statistics">
  <% statistics.each do |statistic| %>
    <div class="statistic">
      <h4><%= statistic.date.strftime('%Y年') %></h4>
      <h4><%= image_tag "#{statistic.weather_condition_d}.png" %><%= image_tag "#{statistic.weather_condition_n}.png" %></h4>
      <h4><span class="max"><%= statistic.temp_max %>℃</span> / <span class="min"><%= statistic.temp_min %>℃</span></h4>
    </div>
  <% end %>
</div>

app/views/weather_forecasts/_template.html.erb
<div class="forecast">
  <div class="forecast-head">
    <span><%= weather_forecasts.first.date.strftime('%m月%d日') %>の天気</span>
    <span class="max"><%= weather_forecasts.maximum(:temp_max).round %>℃</span>
    <span class="min"><%= weather_forecasts.minimum(:temp_min).round %>℃</span>
    <span>体感温度：<%= weather_forecasts.average(:temp_feel).round %>℃</span>
  </div>
  <table>
    <thead>
      <th>時間</th>
      <th>0-3</th>
      <th>3-6</th>
      <th>6-9</th>
      <th>9-12</th>
      <th>12-15</th>
      <th>15-18</th>
      <th>18-21</th>
      <th>21-24</th>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <% weather_forecasts.each do |forecast| %>
          <% if forecast.daytime? %>
            <td><%= image_tag "#{forecast.weather_condition}d.png" %></td>
          <% else %>
            <td><%= image_tag "#{forecast.weather_condition}n.png" %></td>
          <% end %>
        <% end %>
      </tr>
      <tr>
        <td>気温</td>
        <% weather_forecasts.each do |forecast| %>
          <td><%= forecast.temp_avg.round(1) %></td>
        <% end %>
      </tr>
      <tr>
        <td>降水/h</td>
        <% weather_forecasts.each do |forecast| %>
          <td><%= forecast.rainfall ? forecast.rainfall_avg.round(1) : '-' %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/weather_forecasts/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <h1><%= @city.name %>の天気</h1>
  <%= render 'forecast_area', weather_forecasts: @weather_forecasts.today, statistics: @statistics.today %>
  <%= render 'forecast_area', weather_forecasts: @weather_forecasts.tomorrow, statistics: @statistics.tomorrow %>
</div>